### ISSUE TITLE
这个No commit message是怎么弄的？

### ISSUE THREAD

**Issue by axiaoxin** [Quantumzhao/ToDue#2]
![图片](https://user-images.githubusercontent.com/2876405/135405534-b3781018-4083-4ed5-b715-27ede9dc15c7.png)

**Comment by Quantumzhao** [comment]
我是用 VS 的 Git 工具提交的。提交时就在消息那一栏里打了一个空格。

按理说这是个 bug，我也应该好好写 commit message 的，实在惭愧
